=== alloy/ObjectiveBacon/bridgesupport/source/BridgeSupport.dtd
<!-- Entities. -->
<!ENTITY % boolean "(true|false)">
<!ENTITY % type_modifier "(n|o|N)">

<!-- Root element. -->
<!ELEMENT signatures (depends_on|struct|cftype|opaque|constant|string_constant|enum|function|function_alias|informal_protocol|class)*>
<!ATTLIST signatures version CDATA "0.9">

<!-- Dependencies. -->
<!ELEMENT depends_on EMPTY>
<!ATTLIST depends_on path CDATA #REQUIRED>

<!-- Structures. -->
<!ELEMENT struct EMPTY>
<!ATTLIST struct name CDATA #REQUIRED>
<!ATTLIST struct type CDATA #REQUIRED>
<!ATTLIST struct type64 CDATA #IMPLIED>
<!ATTLIST struct opaque %boolean; #IMPLIED>

<!-- Opaques. -->
<!ELEMENT opaque EMPTY>
<!ATTLIST opaque name CDATA #REQUIRED>
<!ATTLIST opaque type CDATA #REQUIRED>
<!ATTLIST opaque type64 CDATA #IMPLIED>

<!-- CFTypes. -->
<!ELEMENT cftype EMPTY>
<!ATTLIST cftype name CDATA #REQUIRED>
<!ATTLIST cftype type CDATA #REQUIRED>
<!ATTLIST cftype type64 CDATA #IMPLIED>
<!ATTLIST cftype gettypeid_func CDATA #IMPLIED>
<!ATTLIST cftype tollfree CDATA #IMPLIED>

<!-- Constants. -->
<!ELEMENT constant EMPTY>
<!ATTLIST constant name CDATA #REQUIRED>
<!ATTLIST constant type CDATA #REQUIRED>
<!ATTLIST constant type64 CDATA #IMPLIED>
<!ATTLIST constant magic_cookie %boolean; #IMPLIED>

<!-- String constants. -->
<!ELEMENT string_constant EMPTY>
<!ATTLIST string_constant name CDATA #REQUIRED>
<!ATTLIST string_constant value CDATA #REQUIRED>
<!ATTLIST string_constant nsstring %boolean; #IMPLIED>

<!-- Enums. -->
<!ELEMENT enum EMPTY>
<!ATTLIST enum name CDATA #REQUIRED>
<!ATTLIST enum value CDATA #IMPLIED>
<!ATTLIST enum value64 CDATA #IMPLIED>
<!ATTLIST enum le_value CDATA #IMPLIED>
<!ATTLIST enum be_value CDATA #IMPLIED>
<!ATTLIST enum ignore %boolean; #IMPLIED>
<!ATTLIST enum suggestion CDATA #IMPLIED>

<!-- Arguments. -->
<!ELEMENT arg (arg*,retval?)>
<!ATTLIST arg index CDATA #IMPLIED>
<!ATTLIST arg type_modifier %type_modifier; #IMPLIED>
<!ATTLIST arg c_array_length_in_arg CDATA #IMPLIED>
<!ATTLIST arg c_array_length_in_retval CDATA #IMPLIED>
<!ATTLIST arg c_array_of_fixed_length CDATA #IMPLIED>
<!ATTLIST arg c_array_delimited_by_null %boolean; #IMPLIED>
<!ATTLIST arg c_array_of_variable_length %boolean; #IMPLIED>
<!ATTLIST arg null_accepted %boolean; #IMPLIED>
<!ATTLIST arg type CDATA #IMPLIED>
<!ATTLIST arg type64 CDATA #IMPLIED>
<!ATTLIST arg function_pointer %boolean; #IMPLIED>
<!ATTLIST arg printf_format %boolean; #IMPLIED>
<!ATTLIST arg sel_of_type CDATA #IMPLIED>
<!ATTLIST arg sel_of_type64 CDATA #IMPLIED>

<!-- Return values. -->
<!ELEMENT retval (arg*, retval?)>
<!ATTLIST retval c_array_length_in_arg CDATA #IMPLIED>
<!ATTLIST retval c_array_of_fixed_length CDATA #IMPLIED>
<!ATTLIST retval c_array_delimited_by_null %boolean; #IMPLIED>
<!ATTLIST retval c_array_of_variable_length %boolean; #IMPLIED>
<!ATTLIST retval already_retained CDATA #IMPLIED>
<!ATTLIST retval type CDATA #IMPLIED>
<!ATTLIST retval type64 CDATA #IMPLIED>
<!ATTLIST retval function_pointer %boolean; #IMPLIED>

<!-- Functions. -->
<!ELEMENT function (arg*,retval?)>
<!ATTLIST function name CDATA #REQUIRED>
<!ATTLIST function variadic %boolean; #IMPLIED>
<!ATTLIST function inline %boolean; #IMPLIED>

<!-- Function aliases. -->
<!ELEMENT function_alias EMPTY>
<!ATTLIST function_alias name CDATA #REQUIRED>
<!ATTLIST function_alias original CDATA #REQUIRED>

<!-- Informal protocols. -->
<!ELEMENT informal_protocol (method*)>
<!ATTLIST informal_protocol name CDATA #REQUIRED>

<!-- Classes. -->
<!ELEMENT class (method*)>
<!ATTLIST class name CDATA #REQUIRED>

<!-- Methods. -->
<!ELEMENT method (arg*,retval?)>
<!ATTLIST method selector CDATA #REQUIRED>
<!ATTLIST method type CDATA #IMPLIED>
<!ATTLIST method type64 CDATA #IMPLIED>
<!ATTLIST method class_method %boolean; #IMPLIED>
<!ATTLIST method ignore %boolean; #IMPLIED>
<!ATTLIST method suggestion CDATA #IMPLIED>
<!ATTLIST method variadic %boolean; #IMPLIED>

=== alloy/ObjectiveBacon/bridgesupport/source/exceptions/SyncServices.xml
<?xml version="1.0"?>
<!DOCTYPE signatures SYSTEM "file://localhost/System/Library/DTDs/BridgeSupport.dtd">
<signatures version="0.9">
  <class name='ISyncClient'>
    <method selector='setSyncAlertHandler:selector:'>
      <arg index='1' sel_of_type="(void)client:(ISyncClient *)client mightWantToSyncEntityNames:(NSArray *)entityNames"/>
    </method>
  </class>
  <class name="ISyncRecordSnapshot">
    <method selector="recordIdentifierForReference:isModified:">
      <arg index="1" type_modifier="o"/>
    </method>
  </class>
  <class name='ISyncSession'>
    <method class_method='true' selector='beginSessionInBackgroundWithClient:entityNames:target:selector:'>
      <arg index='3' sel_of_type="(void)client:(ISyncClient *)can session:(ISyncSession *)session"/>
    </method>
    <method class_method='true' selector='beginSessionInBackgroundWithClient:entityNames:target:selector:lastAnchors:'>
      <arg index='3' sel_of_type="(void)client:(ISyncClient *)can session:(ISyncSession *)session"/>
    </method>
    <method selector='prepareToPullChangesInBackgroundForEntityNames:target:selector:'>
      <arg index='2' sel_of_type="(void)client:(ISyncClient *)can session:(ISyncSession *)session"/>
    </method>
  </class>
  <class name="NSObject">
    <method selector="applyChange:forEntityName:remappedRecordIdentifier:formattedRecord:error:">
      <arg index="2" type_modifier="o"/>
      <arg index="3" type_modifier="o"/>
      <arg index="4" type_modifier="o"/>
    </method>
    <method selector="changedRecordsForEntityName:moreComing:error:">
      <arg index="1" type_modifier="o"/>
      <arg index="2" type_modifier="o"/>
    </method>
    <method selector="changesForEntityName:moreComing:error:">
      <arg index="1" type_modifier="o"/>
      <arg index="2" type_modifier="o"/>
    </method>
    <method selector="deleteAllRecordsForEntityName:error:">
      <arg index="1" type_modifier="o"/>
    </method>
    <method selector="identifiersForRecordsToDeleteForEntityName:moreComing:error:">
      <arg index="1" type_modifier="o"/>
      <arg index="2" type_modifier="o"/>
    </method>
    <method selector="recordsForEntityName:moreComing:error:">
      <arg index="1" type_modifier="o"/>
      <arg index="2" type_modifier="o"/>
    </method>
    <method selector="sessionDriver:didPullAndReturnError:">
      <arg index="1" type_modifier="o"/>
    </method>
    <method selector="sessionDriver:didPushAndReturnError:">
      <arg index="1" type_modifier="o"/>
    </method>
    <method selector="sessionDriver:didRegisterClientAndReturnError:">
      <arg index="1" type_modifier="o"/>
    </method>
    <method selector="sessionDriver:willFinishSessionAndReturnError:">
      <arg index="1" type_modifier="o"/>
    </method>
    <method selector="sessionDriver:willPullAndReturnError:">
      <arg index="1" type_modifier="o"/>
    </method>
    <method selector="sessionDriver:willPushAndReturnError:">
      <arg index="1" type_modifier="o"/>
    </method>
  </class>
</signatures>

=== alloy/ObjectiveBacon/bridgesupport/source/exceptions/QTKit.xml
<?xml version="1.0"?>
<!DOCTYPE signatures SYSTEM "file://localhost/System/Library/DTDs/BridgeSupport.dtd">
<signatures version="0.9">
  <ignored_headers>
    <header>QTCaptureLayer.h</header>
  </ignored_headers>
  <struct name="QTTime"/>
  <struct name="QTTimeRange"/>
  <function name="QTGetTimeInterval">
    <arg index="1" type_modifier="o"/>
  </function>
  <function name="QTGetTimeRecord">
    <arg index="1" type_modifier="o"/>
  </function>
  <class name="QTMedia">
    <method selector="initWithQuickTimeMedia:error:">
      <arg index="0" type_modifier="n"/>
      <arg index="1" type_modifier="o"/>
    </method>
    <method class_method="true" selector="mediaWithQuickTimeMedia:error:">
      <arg index="0" type_modifier="n"/>
      <arg index="1" type_modifier="o"/>
    </method>
  </class>
  <class name="QTMovie">
    <method selector="addChapters:withAttributes:error:">
      <arg index="2" type_modifier="o"/>
    </method>
    <method selector="frameImageAtTime:withAttributes:error:">
      <arg index="2" type_modifier="o"/>
    </method>
    <method selector="initToWritableData:error:">
      <arg index="1" type_modifier="o"/>
    </method>
    <method selector="initToWritableDataReference:error:">
      <arg index="1" type_modifier="o"/>
    </method>
    <method selector="initToWritableFile:error:">
      <arg index="1" type_modifier="o"/>
    </method>
    <method selector="initWithAttributes:error:">
      <arg index="1" type_modifier="o"/>
    </method>
    <method selector="initWithData:error:">
      <arg index="1" type_modifier="o"/>
    </method>
    <method selector="initWithDataReference:error:">
      <arg index="1" type_modifier="o"/>
    </method>
    <method selector="initWithFile:error:">
      <arg index="1" type_modifier="o"/>
    </method>
    <method selector="initWithMovie:timeRange:error:">
      <arg index="2" type_modifier="o"/>
    </method>
    <method selector="initWithPasteboard:error:">
      <arg index="1" type_modifier="o"/>
    </method>
    <method selector="initWithQuickTimeMovie:disposeWhenDone:error:">
      <arg index="0" type_modifier="n"/>
      <arg index="2" type_modifier="o"/>
    </method>
    <method selector="initWithURL:error:">
      <arg index="1" type_modifier="o"/>
    </method>
    <method class_method="true" selector="movieNamed:error:">
      <arg index="1" type_modifier="o"/>
    </method>
    <method class_method="true" selector="movieWithAttributes:error:">
      <arg index="1" type_modifier="o"/>
    </method>
    <method class_method="true" selector="movieWithData:error:">
      <arg index="1" type_modifier="o"/>
    </method>
    <method class_method="true" selector="movieWithDataReference:error:">
      <arg index="1" type_modifier="o"/>
    </method>
    <method class_method="true" selector="movieWithFile:error:">
      <arg index="1" type_modifier="o"/>
    </method>
    <method class_method="true" selector="movieWithPasteboard:error:">
      <arg index="1" type_modifier="o"/>
    </method>
    <method class_method="true" selector="movieWithQuickTimeMovie:disposeWhenDone:error:">
      <arg index="0" type_modifier="n"/>
      <arg index="2" type_modifier="o"/>
    </method>
    <method selector="movieWithTimeRange:error:">
      <arg index="1" type_modifier="o"/>
    </method>
    <method class_method="true" selector="movieWithURL:error:">
      <arg index="1" type_modifier="o"/>
    </method>
    <method selector="writeToFile:withAttributes:error:">
      <arg index="2" type_modifier="o"/>
    </method>
  </class>
  <class name="QTTrack">
    <method selector="initWithQuickTimeTrack:error:">
      <arg index="0" type_modifier="n"/>
      <arg index="1" type_modifier="o"/>
    </method>
    <method class_method="true" selector="trackWithQuickTimeTrack:error:">
      <arg index="0" type_modifier="n"/>
      <arg index="1" type_modifier="o"/>
    </method>
  </class>
  <class name="QTDataReference">
    <method class_method="true" selector="dataReferenceWithDataRef:type:">
      <arg index="0" type_modifier="n"/>
    </method>
    <method selector="initWithDataRef:type:">
      <arg index="0" type_modifier="n"/>
    </method>
    <method selector="setDataRef:">
      <arg index="0" type_modifier="n"/>
    </method>
  </class>
</signatures>

=== alloy/ObjectiveBacon/bridgesupport/old-bridgesupport/exceptions/WebKit.xml
<?xml version="1.0"?>
<!DOCTYPE signatures SYSTEM "file://localhost/System/Library/DTDs/BridgeSupport.dtd">
<signatures version="0.9">
  <struct name="NPByteRange"/>
  <struct name="NPClass"/>
  <struct name="NPEmbedPrint"/>
  <struct name="NPFullPrint"/>
  <struct name="NPNetscapeFuncs"/>
  <struct name="NPObject"/>
  <struct name="NPP_t"/>
  <struct name="NPPluginFuncs"/>
  <struct name="NPPrint"/>
  <struct name="NPRect"/>
  <struct name="NPSavedData"/>
  <struct name="NPStream"/>
  <struct name="NPString"/>
  <struct name="NPVariant"/>
  <struct name="NPWindow"/>
  <struct name="NP_Port" only_in="32"/>
  <function name="HIWebViewCreate">
    <arg index="0" type_modifier="n"/>
  </function>
  <function name="NPN_CreateObject">
    <arg index="0" type_modifier="n"/>
    <arg index="1" type_modifier="n"/>
  </function>
  <function name="NPN_DestroyStream">
    <arg index="0" type_modifier="n"/>
    <arg index="1" type_modifier="n"/>
  </function>
  <function name="NPN_Evaluate">
    <arg index="0" type_modifier="n"/>
    <arg index="1" type_modifier="n"/>
    <arg index="2" type_modifier="n"/>
    <arg index="3" type_modifier="o"/>
  </function>
  <function name="NPN_GetProperty">
    <arg index="0" type_modifier="n"/>
    <arg index="1" type_modifier="n"/>
    <arg index="2" type_modifier="n"/>
    <arg index="3" type_modifier="o"/>
  </function>
  <function name="NPN_GetStringIdentifiers">
    <arg c_array_length_in_arg="1" index="0" type_modifier="n"/>
    <arg c_array_length_in_arg="1" index="2" type_modifier="o"/>
  </function>
  <function name="NPN_GetURLNotify">
    <arg index="0" type_modifier="n"/>
    <arg index="3" type_modifier="n"/>
  </function>
  <function name="NPN_GetValue">
    <arg index="0" type_modifier="n"/>
    <arg index="2" type_modifier="o"/>
  </function>
  <function name="NPN_HasMethod">
    <arg index="0" type_modifier="n"/>
    <arg index="1" type_modifier="n"/>
    <arg index="2" type_modifier="n"/>
  </function>
  <function name="NPN_HasProperty">
    <arg index="0" type_modifier="n"/>
    <arg index="1" type_modifier="n"/>
    <arg index="2" type_modifier="n"/>
  </function>
  <function name="NPN_InvalidateRect">
    <arg index="0" type_modifier="n"/>
    <arg index="1" type_modifier="n"/>
  </function>
  <function name="NPN_Invoke">
    <arg index="0" type_modifier="n"/>
    <arg index="1" type_modifier="n"/>
    <arg index="2" type_modifier="n"/>
    <arg c_array_length_in_arg="4" index="3" type_modifier="n"/>
    <arg index="5" type_modifier="o"/>
  </function>
  <function name="NPN_InvokeDefault">
    <arg index="0" type_modifier="n"/>
    <arg index="1" type_modifier="n"/>
    <arg c_array_length_in_arg="3" index="2" type_modifier="n"/>
    <arg index="4" type_modifier="o"/>
  </function>
  <function name="NPN_MemFree">
    <arg index="0" type_modifier="n"/>
  </function>
  <function name="NPN_NewStream">
    <arg index="0" type_modifier="n"/>
    <arg index="3" type_modifier="o"/>
  </function>
  <function name="NPN_PostURLNotify">
    <arg index="0" type_modifier="n"/>
    <arg index="6" type_modifier="n"/>
  </function>
  <function name="NPN_ReleaseObject">
    <arg index="0" type_modifier="n"/>
  </function>
  <function name="NPN_ReleaseVariantValue">
    <arg index="0" type_modifier="n"/>
  </function>
  <function name="NPN_RemoveProperty">
    <arg index="0" type_modifier="n"/>
    <arg index="1" type_modifier="n"/>
    <arg index="2" type_modifier="n"/>
  </function>
  <function name="NPN_RequestRead">
    <arg index="0" type_modifier="n"/>
    <arg index="1" type_modifier="n"/>
  </function>
  <function name="NPN_RetainObject">
    <arg index="0" type_modifier="n"/>
  </function>
  <function name="NPN_SetException">
    <arg index="0" type_modifier="n"/>
  </function>
  <function name="NPN_SetProperty">
    <arg index="0" type_modifier="n"/>
    <arg index="1" type_modifier="n"/>
    <arg index="2" type_modifier="n"/>
    <arg index="3" type_modifier="n"/>
  </function>
  <function name="NPN_SetValue">
    <arg index="0" type_modifier="n"/>
    <arg index="2" type_modifier="n"/>
  </function>
  <function name="NPN_Version">
    <arg index="0" type_modifier="o"/>
    <arg index="1" type_modifier="o"/>
    <arg index="2" type_modifier="o"/>
    <arg index="3" type_modifier="o"/>
  </function>
  <function name="NPN_Write">
    <arg index="0" type_modifier="n"/>
    <arg index="1" type_modifier="n"/>
    <arg c_array_length_in_arg="2" index="3" type_modifier="n"/>
  </function>
  <function name="NPP_DestroyStream">
    <arg index="0" type_modifier="n"/>
    <arg index="1" type_modifier="n"/>
  </function>
  <function name="NPP_GetValue">
    <arg index="0" type_modifier="n"/>
    <arg index="2" type_modifier="o"/>
  </function>
  <function name="NPP_HandleEvent">
    <arg index="0" type_modifier="n"/>
    <arg index="1" type_modifier="n"/>
  </function>
  <function name="NPP_New">
    <arg index="1" type_modifier="n"/>
    <arg c_array_length_in_arg="3" index="4" type_modifier="n"/>
    <arg c_array_length_in_arg="3" index="5" type_modifier="n"/>
    <arg index="6" type_modifier="n"/>
  </function>
  <function name="NPP_NewStream">
    <arg index="0" type_modifier="n"/>
    <arg index="2" type_modifier="n"/>
    <arg index="4" type_modifier="N"/>
  </function>
  <function name="NPP_Print">
    <arg index="0" type_modifier="n"/>
    <arg index="1" type_modifier="o"/>
  </function>
  <function name="NPP_SetValue">
    <arg index="0" type_modifier="n"/>
    <arg index="2" type_modifier="n"/>
  </function>
  <function name="NPP_SetWindow">
    <arg index="0" type_modifier="n"/>
    <arg index="1" type_modifier="n"/>
  </function>
  <function name="NPP_StreamAsFile">
    <arg index="0" type_modifier="n"/>
    <arg index="1" type_modifier="o"/>
  </function>
  <function name="NPP_URLNotify">
    <arg index="0" type_modifier="n"/>
    <arg index="3" type_modifier="n"/>
  </function>
  <function name="NPP_Write">
    <arg index="0" type_modifier="n"/>
    <arg index="1" type_modifier="n"/>
    <arg c_array_of_fixed_length="3" index="4" type_modifier="n"/>
  </function>
  <function name="NPP_WriteReady">
    <arg index="0" type_modifier="n"/>
    <arg index="1" type_modifier="n"/>
  </function>
  <function name="NPN_ForceRedraw">
    <arg index="0" type_modifier="n"/>
  </function>
  <function name="NPN_GetJavaPeer">
    <arg index="0" type_modifier="n"/>
  </function>
  <function name="NPN_GetURL">
    <arg index="0" type_modifier="n"/>
  </function>
  <function name="NPN_IdentifierIsString">
    <arg index="0" type_modifier="n"/>
  </function>
  <function name="NPN_IntFromIdentifier">
    <arg index="0" type_modifier="n"/>
  </function>
  <function name="NPN_InvalidateRegion">
    <arg index="0" type_modifier="n"/>
    <arg index="1" type_modifier="n"/>
  </function>
  <function name="NPN_PostURL">
    <arg index="0" type_modifier="n"/>
  </function>
  <function name="NPN_Status">
    <arg index="0" type_modifier="n"/>
  </function>
  <function name="NPN_UTF8FromIdentifier">
    <arg index="0" type_modifier="n"/>
  </function>
  <function name="NPN_UserAgent">
    <arg index="0" type_modifier="n"/>
  </function>
  <function name="NPP_Destroy">
    <arg index="0" type_modifier="n"/>
    <arg index="1" type_modifier="o"/>
  </function>
  <class name="NSObject">
    <method selector="webPlugInCallJava:isStatic:returnType:method:arguments:callingURL:exceptionDescription:">
      <arg index="0" type_modifier="n"/>
      <arg index="3" type_modifier="n"/>
      <arg index="4" c_array_of_variable_length="true" type_modifier="n"/>
      <arg index="6" type_modifier="o"/>
    </method>
  </class>
  <class name="WebHistory">
    <method selector="loadFromURL:error:">
      <arg index="1" type_modifier="o"/>
    </method>
    <method selector="saveToURL:error:">
      <arg index="1" type_modifier="o"/>
    </method>
  </class>
</signatures>

=== alloy/ObjectiveBacon/bridgesupport/source/exceptions/QuartzCore.xml
<?xml version="1.0"?>
<!DOCTYPE signatures SYSTEM "file://localhost/System/Library/DTDs/BridgeSupport.dtd">
<signatures version="0.9">
  <ignored_headers>
    <header>LKObsolete.h</header>
  </ignored_headers>
  <cftype name="CVBufferRef"/>
  <cftype name="CVDisplayLinkRef" gettypeid_func="CVDisplayLinkGetTypeID"/>
  <cftype name="CVOpenGLBufferPoolRef" gettypeid_func="CVOpenGLBufferPoolGetTypeID"/>
  <cftype name="CVOpenGLTextureCacheRef" gettypeid_func="CVOpenGLTextureCacheGetTypeID"/>
  <cftype name="CVPixelBufferPoolRef" gettypeid_func="CVPixelBufferPoolGetTypeID"/>
  <struct name="CVFillExtendedPixelsCallBackData"/>
  <struct name="CVSMPTETime"/>
  <struct name="CVTime"/>
  <struct name="CVTimeStamp"/>
  <function name="CVBufferGetAttachment">
    <arg index="2" type_modifier="o"/>
  </function>
  <function name="CVDisplayLinkCreateWithActiveCGDisplays">
    <arg index="0" type_modifier="o"/>
  </function>
  <function name="CVDisplayLinkCreateWithCGDisplay">
    <arg index="1" type_modifier="o"/>
  </function>
  <function name="CVDisplayLinkCreateWithCGDisplays">
    <arg c_array_length_in_arg="1" index="0" type_modifier="n"/>
    <arg index="2" type_modifier="o"/>
  </function>
  <function name="CVDisplayLinkCreateWithOpenGLDisplayMask">
    <arg index="1" type_modifier="o"/>
  </function>
  <function name="CVDisplayLinkGetCurrentTime">
    <arg index="1" type_modifier="o"/>
  </function>
  <function name="CVDisplayLinkSetOutputCallback">
    <arg index="1" type_modifier="n"/>
    <arg index="2" type_modifier="n"/>
  </function>
  <function name="CVDisplayLinkTranslateTime">
    <arg index="1" type_modifier="n"/>
    <arg index="2" type_modifier="o"/>
  </function>
  <function name="CVOpenGLBufferCreate">
    <arg index="4" type_modifier="o"/>
  </function>
  <function name="CVOpenGLBufferPoolCreate">
    <arg index="3" type_modifier="o"/>
  </function>
  <function name="CVOpenGLBufferPoolCreateOpenGLBuffer">
    <arg index="2" type_modifier="o"/>
  </function>
  <function name="CVOpenGLTextureCacheCreate">
    <arg index="2" type_modifier="n"/>
    <arg index="3" type_modifier="n"/>
    <arg index="5" type_modifier="o"/>
  </function>
  <function name="CVOpenGLTextureCacheCreateTextureFromImage">
    <arg index="2" type_modifier="n"/>
    <arg index="3" type_modifier="n"/>
    <arg index="4" type_modifier="o"/>
  </function>
  <function name="CVOpenGLTextureGetCleanTexCoords">
    <arg c_array_of_fixed_length="2" index="1" type_modifier="o"/>
    <arg c_array_of_fixed_length="2" index="2" type_modifier="o"/>
    <arg c_array_of_fixed_length="2" index="3" type_modifier="o"/>
    <arg c_array_of_fixed_length="2" index="4" type_modifier="o"/>
  </function>
  <function name="CVPixelBufferCreate">
    <arg index="5" type_modifier="o"/>
  </function>
  <function name="CVPixelBufferCreateResolvedAttributesDictionary">
    <arg index="2" type_modifier="o"/>
  </function>
  <function name="CVPixelBufferCreateWithBytes">
    <arg index="4" type_modifier="n" c_array_of_variable_length='true'/>
    <arg index="7" type_modifier="n"/>
    <arg index="9" type_modifier="o"/>
  </function>
  <function name="CVPixelBufferCreateWithPlanarBytes">
    <arg index="4" type_modifier="n"/>
    <arg index="7" c_array_of_variable_length="true" type_modifier="n"/>
    <arg index="8" c_array_of_variable_length="true" type_modifier="n"/>
    <arg index="9" c_array_of_variable_length="true" type_modifier="n"/>
    <arg index="10" c_array_of_variable_length="true" type_modifier="n"/>
    <arg index="11" type_modifier="n"/>
    <arg index="12" type_modifier="n"/>
    <arg index="14" type_modifier="o"/>
  </function>
  <function name="CVPixelBufferGetExtendedPixels">
    <arg index="1" type_modifier="o"/>
    <arg index="2" type_modifier="o"/>
    <arg index="3" type_modifier="o"/>
    <arg index="4" type_modifier="o"/>
  </function>
  <function name="CVPixelBufferPoolCreate">
    <arg index="3" type_modifier="o"/>
  </function>
  <function name="CVPixelBufferPoolCreatePixelBuffer">
    <arg index="2" type_modifier="o"/>
  </function>
  <function name="CVDisplayLinkSetCurrentCGDisplayFromOpenGLContext">
    <arg index="1" type_modifier="n"/>
    <arg index="2" type_modifier="n"/>
  </function>
  <function name="CVOpenGLBufferAttach">
    <arg index="1" type_modifier="n"/>
  </function>
  <class name="CIContext">
    <method selector="render:toBitmap:rowBytes:bounds:format:colorSpace:">
      <arg index="1" type_modifier="n"/>
    </method>
  </class>
  <class name='CIKernel'>
    <method selector='setROISelector:'>
      <arg index='0' sel_of_type="(CGRect)regionOf:(int)samplerIndex destRect:(CGRect)r userInfo:(id)obj"/>
    </method>
  </class>
  <class name="CIVector">
    <method selector="initWithValues:count:">
      <arg c_array_length_in_arg="1" index="0" type_modifier="n"/>
    </method>
    <method class_method="true" selector="vectorWithValues:count:">
      <arg c_array_length_in_arg="1" index="0" type_modifier="n"/>
    </method>
  </class>
  <class name="NSObject">
    <method selector="load:">
      <arg index="0" type_modifier="n"/>
    </method>
    <method selector="provideImageData:bytesPerRow:origin:size:userInfo:">
      <arg index="0" type_modifier="n"/>
    </method>
  </class>
</signatures>

=== alloy/ObjectiveBacon/bridgesupport/old-bridgesupport/exceptions/CoreData.xml
<?xml version="1.0"?>
<!DOCTYPE signatures SYSTEM "file://localhost/System/Library/DTDs/BridgeSupport.dtd">
<signatures version="0.9">
  <class name="NSManagedObject">
    <method selector="setObservationInfo:">
      <arg index="0" type_modifier="n"/>
    </method>
    <method selector="validateForDelete:">
      <arg index="0" type_modifier="o"/>
    </method>
    <method selector="validateForInsert:">
      <arg index="0" type_modifier="o"/>
    </method>
    <method selector="validateForUpdate:">
      <arg index="0" type_modifier="o"/>
    </method>
    <method selector="validateValue:forKey:error:">
      <arg index="0" type_modifier="o"/>
      <arg index="2" type_modifier="o"/>
    </method>
  </class>
  <class name="NSManagedObjectContext">
    <method selector="countForFetchRequest:error:">
      <arg index="1" type_modifier="o"/>
    </method>
    <method selector="executeFetchRequest:error:">
      <arg index="1" type_modifier="o"/>
    </method>
    <method selector="observeValueForKeyPath:ofObject:change:context:">
      <arg index="3" type_modifier="n"/>
    </method>
    <method selector="obtainPermanentIDsForObjects:error:">
      <arg index="1" type_modifier="o"/>
    </method>
    <method selector="save:">
      <arg index="0" type_modifier="o"/>
    </method>
  </class>
  <class name="NSPersistentStoreCoordinator">
    <method selector="addPersistentStoreWithType:configuration:URL:options:error:">
      <arg index="4" type_modifier="o"/>
    </method>
    <method class_method="true" selector="metadataForPersistentStoreOfType:URL:error:">
      <arg index="2" type_modifier="o"/>
    </method>
    <method class_method="true" selector="metadataForPersistentStoreWithURL:error:">
      <arg index="1" type_modifier="o"/>
    </method>
    <method selector="migratePersistentStore:toURL:options:withType:error:">
      <arg index="4" type_modifier="o"/>
    </method>
    <method selector="removePersistentStore:error:">
      <arg index="1" type_modifier="o"/>
    </method>
    <method class_method="true" selector="setMetadata:forPersistentStoreOfType:URL:error:">
      <arg index="3" type_modifier="o"/>
    </method>
  </class>
</signatures>

=== alloy/ObjectiveBacon/bridgesupport/source/exceptions/AddressBook.xml
<?xml version="1.0"?>
<!DOCTYPE signatures SYSTEM "file://localhost/System/Library/DTDs/BridgeSupport.dtd">
<signatures version="0.9">
  <!-- those AB*Ref CFTypes miss a gettypeid function (rdar://4908162) -->
  <cftype name="ABAddressBookRef"/>
  <cftype name="ABGroupRef"/>
  <cftype name="ABMultiValueRef"/>
  <cftype name="ABMutableMultiValueRef"/>
  <cftype name="ABPersonRef"/>
  <cftype name="ABPickerRef"/>
  <cftype name="ABSearchElementRef"/>
  <struct name="ABActionCallbacks"/>
  <opaque name="ABRecordRef" ignore="true" type="@"/>
  <function name="ABBeginLoadingImageDataForClient">
    <arg index="1" type_modifier="n"/>
    <arg index="2" type_modifier="n"/>
  </function>
  <function name="ABMultiValueAdd">
    <arg index="3" type_modifier="o"/>
  </function>
  <function name="ABMultiValueInsert">
    <arg index="4" type_modifier="o"/>
  </function>
  <function name="ABPickerGetFrame">
    <arg index="1" type_modifier="o"/>
  </function>
  <function name="ABPickerSetFrame">
    <arg index="1" type_modifier="n"/>
  </function>
  <class name="ABAddressBook">
    <method selector="saveAndReturnError:">
      <arg index="0" type_modifier="o"/>
    </method>
  </class>
  <class name='ABPeoplePickerView'>
    <method selector='setGroupDoubleAction:'>
      <arg index='0' sel_of_type="(void)doubleAction:(id)sender"/>
    </method>
    <method selector='setNameDoubleAction:'>
      <arg index='0' sel_of_type="(void)doubleAction:(id)sender"/>
    </method>
  </class>
</signatures>
